[package]

name = "mailcheck"
version = "0.0.1"
authors = ["Scott McKay <scottm@mailchannels.com>"]

[dependencies]

time = "*"
encoding = "*"
openssl = "*"
regex = "*"
regex_macros = "*"
rustc-serialize = "*"
